# fly.toml app configuration file generated for portfoliowebsite on 2024-01-XX

app = 'portfoliowebsite'
primary_region = 'ams'

[build]

[env]
  PORT = '80'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# Add your custom domain here (uncomment and replace with your domain)
# [[services]]
#   protocol = "tcp"
#   internal_port = 80
#   [[services.ports]]
#     port = 80
#     handlers = ["http"]
#   [[services.ports]]
#     port = 443
#     handlers = ["tls", "http"]
#   [[services.tcp_checks]]
#     interval = "15s"
#     timeout = "2s"
#     grace_period = "1s"
#   [[services.http_checks]]
#     interval = "10s"
#     timeout = "2s"
#     grace_period = "1s"
#     method = "get"
#     path = "/"
#     protocol = "http"
#     tls_skip_verify = false

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
